README.md
The "<\/img>" tag is incorrect, so I help to remove it.
=> Remove incorrect tag

src/Application/Console/Analyser.php, src/Infrastructure/Repositories/LocalFilesRepository.php
This pull request removes some current unused imports.
=> Remove unused imports

src/Application/Console/Style.php
This would also require to update the [image](https://raw.githubusercontent.com/nunomaduro/phpinsights/master/docs/banner.png) in your README.
=> fix: fix typo

README.md
=> Remove php prefix and add Windows bat version

README.md
Suggest usage of [bamarni/composer-bin-plugin](https://github.com/bamarni/composer-bin-plugin) to help users with dependencies conflicts. 
This should help for issues #56 and #74
WDYT ?
=> Docs: Add note about Avoid composer conflicts

.travis.yml
=> Insight on phpinsights

README.md
Modified `README.md` to clarify example how to execute with `docker` 
This will make it easier for those who are copy/pasting command.  If the user is more experienced with docker, they will know what to change :-)
=> update README, providing copy/paste example for docker execution

README.md
| Documentation?| yes
| Fixed tickets | no
Having to navigate to the website to get started quickly is kinda redundant, so I've just added the quick start sample to the repo's README.md
=> Added Quick Start section to the README.md

README.md
|Documentation | yes
Includes Docker instructions in README Quick Start section
=> update README, add Docker instructions to QuickStart section

src/Domain/Metrics/Architecture/Namespaces.php
=> Remove duplicate NamespaceDeclarationSniff

RELEASE.md
Describes the steps to verify before publishing a new release.
Discussed in #136
=> Add a release process

src/Application/DefaultPreset.php
Add's in the folders and files which I mentioned in issue #143.
=> [Feat] Add folders/files to default exclude

CHANGELOG.md, docs/package.json, src/Domain/Kernel.php
=> Bumps version to 1.6.0

docs/.vuepress/components/Testimonial.vue, docs/.vuepress/config.js, docs/.vuepress/style.styl, docs/testimonial.md
| Documentation | yes
| Fixed tickets | #161 
Added "What others think about PHP Insights" below the `get started` section
FYI, I need to make additional components to make the Twitter widgets.js working 😄
=> Added "What other think about PHP Insights" page on the website

docs/.vuepress/config.js, docs/insights/README.md, docs/insights/architecture.md, docs/insights/code.md, docs/insights/complexity.md, docs/insights/style.md, docs/support.md
=> docs: explain how to config and list of used insights

phpinsights.php
| Fixed tickets | #184 
Change the default line limit to 80/120.
resolves: #184
=> internal: Change default line limit

src/Application/ConfigResolver.php
This pull request fixes `PHP Notice:  Undefined offset: 0 in /Users/nunomaduro/Work/phpinsights/src/Application/ConfigResolver.php on line 99`. Not sure when it happens, can you double check this pull request @Jibbarth ?
=> Fixes non defined key on config resolver

README.md
This pull request adds contributors on the readme.
=> Adds missing contributors on readme

tests/TestCase.php
Use single quote by default instead of double quote.
=> Use single quote

docs/insights/README.md
Just a quick little fix to a typo in a code snippet
=> [Docs] Fix string not being closed in code snippet

tests/Domain/ResultsTest.php, tests/Domain/Sniffs/ForbiddenSetterMethods/ForbiddenSetterMethodsTest.php
This PR just moves some unused imports.
=> cs: Remove unused imports

src/Application/Console/Formatters/Console.php
That PR take in account the terminal width to adapt block score and percentage line.
=> [Feat] Responsive view for console output

src/Application/Console/Definitions/AnalyseDefinition.php, src/Application/Console/Formatters/Checkstyle.php
| Fixed tickets | #274
Add encoding to xml and update console help description
=> Fix checkstyle formatter

docs/continuous-integration.md, docs/contribute.md, docs/get-started.md, docs/insights/README.md, docs/insights/architecture.md, docs/insights/code.md, docs/insights/complexity.md, docs/insights/style.md
| Fixed tickets | no
I fixed some Grammer errors I found in the docs while reading through them.
=> Fixed some Grammer errors in the documentation.

docs/support.md
Add our new [OpenCollective page](https://opencollective.com/phpinsights) to support page
=> Add openCollective to support page

src/Domain/Insights/ForbiddenSecurityIssues.php
| Fixed tickets | #229 
This fix remove the exception raised when there is no internet connection to keep display other errors.
People can now improve their projects while traveling :flight_departure:
=> Refs #229 - non blocking exception when no internet connection

docs/insights/architecture.md, docs/insights/code.md, src/Domain/Metrics/Architecture/Functions.php, src/Domain/Metrics/Code/Functions.php
This pull request fixes the category of the return type fixer
=> fix(return-type-fixer): return type fixer in wrong category

tests/Domain/Insights/ForbiddenGlobalsTest.php
| Fixed tickets | no
Adds missing declaration
=> Missing declaration

docs/insights/style.md, src/Domain/Metrics/Style/Style.php
| Fixed tickets | #299 
Remove duplicate
=> ForbiddenFunctionsSniff

src/Application/DefaultPreset.php
=> Fix UnusedVariableSniff

CHANGELOG.md, docs/package.json, src/Domain/Kernel.php
| Fixed tickets | #305
:sparkles:
=> [Release] 1.10.0

CHANGELOG.md, docs/package.json, src/Domain/Kernel.php
=> [Release] 1.10.1

src/Domain/Insights/ForbiddenDefineFunctions.php, src/Domain/Insights/ForbiddenTraits.php, tests/Domain/Insights/Fixtures/MyTrait.php, tests/Domain/Insights/ForbiddenTraitsTest.php
=> [Fix] forbidden trait exclude

CHANGELOG.md, docs/package.json, src/Domain/Kernel.php
=> [Release] 1.10.2

CHANGELOG.md, docs/package.json, src/Domain/Kernel.php
=> [Release] 1.10.3

composer.json
| Fixed tickets | -
Introducing Symfony 5 support
#SymfonyHackday
=> Support Symfony 5

CHANGELOG.md, docs/package.json, src/Domain/Kernel.php
| Release ?     | yes
To release fix for #325
=> [Release] 1.11.1

src/Domain/Runner.php
=> Minor grammar fix

src/Application/Console/Formatters/Console.php
| Fixed tickets | #336
This will add coloring to the File:line output, as we discuss in the related issue #336 I picked a combination of colors at based on the 'severity' of the categories.
=> [WIP]Text coloring when there is a file:line in the output

src/Domain/Analyser.php
=> Fix incorrect variable name

tests/Domain/Sniffs/ForbiddenSetterMethods/ForbiddenSetterMethodsTest.php, tests/Feature/Laravel/ClassesTest.php, tests/Infrastructure/Repositories/LocalFilesRepositoryTest.php
- Fix some double quotes to increase consistency & code quality.
=> Fix some double quotes for more consistency & quality

docs/get-started.md
resume is a false friend for romance languages
https://en.wikipedia.org/wiki/False_friend
=> fixed typo (false friend)

src/Application/ConfigResolver.php, tests/Application/ConfigResolverTest.php
| Fixed tickets | #398 
This PR will close #398.
=> Override preset by config

composer.json, src/Domain/Collector.php
=> Update composer version

composer.json
=> allow phploc version 7

composer.json, docs/insights/architecture.md, src/Domain/Metrics/Architecture/Functions.php
| Fixed tickets | #488 
This PR will close #488.
=> Fix FunctionLengthSniff namespace

docs/insights/architecture.md
| New feature?  no
| Fixed tickets | #506
=> Fix docs wrong namespace

docs/get-started.md, docs/insights/README.md, docs/insights/code.md
| Fixed tickets | n/a
Just cleaning up some typos and grammar in the docs
=> docs: typofixes

src/Domain/Insights/ForbiddenGlobals.php, tests/Domain/Insights/ForbiddenGlobalsTest.php
| Fixed tickets | #560 
This PR will close #560.
=> Fix exclude ForbiddenGlobals sniff

docs/insights/README.md
| Fixed tickets | #532 
In this pull request I’ve updated documentation by describing how to exclude insight per particular method.
=> Describe how to exclude insight per particular method

docs/get-started.md, docs/insights/README.md
I found and fixed a couple of typos and wording issues :-)
=> Fixed some wording and typos

stubs/config.php
makes a text change that reads better in English
| Bug fix?      |  no
=> grammar change

docs/readme.md
=> Update readme.md to 2023

.github/workflows/docker.yaml, .github/workflows/frameworks.yaml, .github/workflows/test.yaml, phpunit.xml, phpunit9.xml
Add missing L10 tests and use new v3 action.
=> Update GitHub actions

.github/workflows/frameworks.yaml, .github/workflows/standalone.yaml, .github/workflows/test.yaml
| Fixed tickets | -
Test against php 8.3 (Unit Tests, Standalone and Popular Frameworks workflows)
=> Test against php 8.3

composer.json
| Fixed tickets | #678 #676 #693
Add support to the newest sebastian/diff version
=> Add support for sebastian/diff 6.0

src/Application/Adapters/Laravel/Commands/InsightsCommand.php, src/Application/Console/Commands/InvokableCommand.php
Fix grammar in the "Subscribe to my YouTube channel" funding messages.
=> chore: fix grammar in "subscribe to youtube" funding messages
