.travis.yml
composer.json

We can compose all tests into only one composer script. Let's see how convenient it is.
```bash
$ composer run --list
scripts:
ecs:test      Run the ecs tests.                        
phpstan:test  Run the phpstan tests.                    
test          Run all tests including phpstan and ecs.
$ composer run test
> phpstan analyse --ansi
Note: Using configuration file /home/xuanquynh/Documents/Projects/nunomaduro/phpinsights/phpstan.neon.dist.
83/83 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
[OK] No errors                                                                 
> ecs check src --ansi --config vendor/symplify/easy-coding-standard/config/clean-code.yml
EasyCodingStandard v5.4.16
Config file: /home/xuanquynh/Documents/Projects/nunomaduro/phpinsights/vendor/symplify/easy-coding-standard/con …
```

Add test composer script

---

phpinsights

- Because the executable file is placed under the package directory, it is located at `vendor/nunomaduro/phpinsights/phpinsights` when this package is installed as a dependency. Therefore, you have to go back 2 steps in directory to see the `autoload.php` file, not 3 steps.
- The console run method will create an ArgvInput automatically if you don't pass any inputs into it. Therefore, you needn't to care about the input instance this situation. See [this line](https://github.com/symfony/symfony/blob/6e8529f82ec4c7ddb99c6330c0443ed4e0efbb48/src/Symfony/Component/Console/Application.php#L115) for the details!

Clean phpinsights executable file

---

src/Application/Adapters/Laravel/Preset.php

This adds `dd` and `dump` to the forbidden functions in the [Laravel preset](https://github.com/pxgamer/phpinsights/blob/111bd7bfd9f5b7b378e58176265d965266dbf066/src/Application/Adapters/Laravel/Preset.php).
I've tested it locally. I did try using the code mentioned in https://github.com/nunomaduro/phpinsights/issues/12#issuecomment-490576671, however this didn't seem to work correctly.
Closes #12
----
P.S. I don't think this follows the Style CI guidelines for Symfony, but not sure that's actually enabled as the rest of the code also doesn't follow it.

Add forbidden dump functions to Laravel preset

---

src/Application/Console/Style.php

Hello, 
When launching insight with `--no-interaction` option, there is still a prompt to see issues.
I added a check on InputInterface `isInteractive()` in waitForKey function to prevent this.

Take in account no-interaction option

---

src/Application/Adapters/Laravel/Preset.php

In addition to #46 it would be nice to ignore the _ide_helper_models.php file too, generated by the same package, as alot of errors are coming from this helper file.

Ignore ide_helper_models

---

composer.json
src/Application/Console/Style.php
tests/Application/Console/StyleTest.php
tests/TestCase.php

This PR add's padding to the percentage string so the length is always 5
resolves: #22

[Fix] Added padding to percentage string

---

src/Application/Adapters/Laravel/Preset.php
src/Application/Adapters/Symfony/Preset.php
src/Application/Adapters/Yii/Preset.php
tests/Application/ConfigResolverTest.php
tests/Fixtures/ConfigResolver/ComposerLaravel/composer.json
tests/Fixtures/ConfigResolver/ComposerSymfony/composer.json
tests/Fixtures/ConfigResolver/ComposerWithoutRequire/composer.json
tests/Fixtures/ConfigResolver/ComposerYii/composer.json

Check if composer require is setted and contains an array
Add tests on ConfigResolver::guess

Fix issue #70

---

README.md
config/routes/console.php
src/Application/Console/Analyser.php
src/Application/Console/Commands/AnalyseCommand.php
src/Application/Console/Commands/InvokableCommand.php

Refs #60 , implements exit status code and min levels to reach.
```bash
$ php bin/phpinsights --help                               
Usage:
analyse [options] [--] [<directory>]
Arguments:
directory                                  
Options:
-c, --config-path[=CONFIG-PATH]            
--min-quality[=MIN-QUALITY]            Minimal Quality level to reach without throw error [default: 0]
--min-complexity[=MIN-COMPLEXITY]      Minimal Complexity level to reach without throw error [default: 0]
--min-architecture[=MIN-ARCHITECTURE]  Minimal Architecture level to reach without throw error [default: 0]
--min-style[=MIN-STYLE]                Minimal Style level to reach without throw error [default: 0]
-h, --help                                 Display this help message
-q, --quiet …
```

Add exit status code - #60

---

composer.json

Addresses #72. nette/utils doesn't explicit require it because they provide too many things, but they do suggest it (https://github.com/nette/utils/blob/master/composer.json#L25). Since it's part of the core process of Insight to use `Strings::webalize`, it makes sense for Insights to require it on installation time instead of delegating to Runtime since Insights cannot work at all without it.

Require necessary extension

---

.dockerignore
README.md
docker/Dockerfile

Since not all projects can be updated to php 7.2, I've dockerized this package.
It would be interesting to create a stage in the CI pipeline and push the image on the docker hub

dockerized

---

stubs/config.php
stubs/laravel.php
stubs/symfony.php

This will help people to know how to exclude certain files / directories. Eg. within Symfony people usually want to exclude `src/Migrations` directory totally just because it contains generated files.

Add exclude key to default stub

---

composer.json

| Bug fix?      | no 
| Improvment?   | yes
As others script ran by Composer, I add the `--ansi` option to insight to get colors in travis build output.

Add --ansi option to insights script in composer.json

---

src/Application/Console/Commands/AnalyseCommand.php

I think when security issues are detected, we should in every case return an exit error code

Add exit status code error when detect Security Issues

---

src/Application/Adapters/Laravel/Preset.php

Ignore TelescopeServiceProvider in the Laravel Preset.
Closes #110

Ignore TelescopeServiceProvider

---

.travis.yml
composer.json
docs/continuous-integration.md
src/Application/Console/Commands/AnalyseCommand.php
src/Application/Console/Definitions/AnalyseDefinition.php

| Fixed tickets | see PR #106
Add `--disable-security-check` to bypass exit error code introduced in #106 when vulnerability is detected.

Add option to disable security issues check

---

src/Application/ConfigResolver.php

Currently it's not possible to overwrite an existing config from the preset. The following example will produce the following error:
```php
<?php declare(strict_types=1);
use SlevomatCodingStandard\Sniffs\TypeHints\DeclareStrictTypesSniff;
return [
'preset' => 'default',
'config' => [
DeclareStrictTypesSniff::class => [
'newlinesCountBetweenOpenTagAndDeclare' => 0,
],
],
];
```
`
PHP Notice:  Array to string conversion in <path>/phpinsights/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/SniffSettingsHelper.php on line 21
`
The reason for this problem is that `array_merge_recursive` merges two values into an array instead of replacing it. `array_replace_recursive` will replace the setting instead of creating an …

Fix issue with overwrite of existing preset config options

---

composer.json
src/Domain/EcsContainer.php

| Fixed tickets | #123 
Refs @TomasVotruba response (https://github.com/nunomaduro/phpinsights/issues/123#issuecomment-494683841) I change the way to create EcsContainer to avoid bug using shortcut for config-path.

Fix create EcsContainer

---

src/Application/Console/Style.php
src/Domain/Contracts/Insight.php
src/Domain/Exceptions/SniffClassNotFound.php
src/Domain/Insights/Insight.php
src/Domain/Insights/Sniff.php

| Fixed tickets | #137 
Display Insight FQCN for each section to help users to know wich Sniff/Insight is applied

Display insight class name (#137)

---

docs/.vuepress/config.js

This adds a link to the GitHub repository from the navigation bar of the VuePress site.

Add GitHub link to the VuePress navbar

---

src/Domain/Analyser.php

| Fixed tickets | #134 
This PR fixes incorrect calculation of cyclomatic complexity when using type hint in arguments and return value in functions declaration

Fix incorrect cyclomatic complexity calculation (#134)

---

src/Infrastructure/Repositories/LocalFilesRepository.php
tests/Infrastructure/Repositories/Fixtures/FolderWithBladeFile/login.blade.php
tests/Infrastructure/Repositories/LocalFilesRepositoryTest.php

| Fixed tickets | #59 
This PR adds support for ignore blade files.

[Feat] Ignore blade files

---

composer.json

Just updates the security-checker from sensiolabs reported by the dependabot.

Update sensiolabs/security-checker requirement from ^5.0 to ^6.0

---

src/Application/Console/Style.php

When an Insight doesn't implement HasDetail, we cannot see it's Class with `-v` option.
```
// example
• [Architecture] Property per class limit: (ObjectCalisthenics\Sniffs\Metrics\PropertyPerClassLimitSniff)
src/Domain/Collector.php:13: "class" has too many properties: 40. Can be up to 10 properties.
• [Architecture] The name property in the `composer.json` contains the default value
```
This fix allow that 
```
• [Architecture] Property per class limit: (ObjectCalisthenics\Sniffs\Metrics\PropertyPerClassLimitSniff)
src/Domain/Collector.php:13: "class" has too many properties: 40. Can be up to 10 properties.
• [Architecture] The name property in the `composer.json` contains the …
```

Display InsightClass also when Insight has no detail

---

.gitignore
composer.json
src/Domain/ComposerFinder.php
src/Domain/ComposerLoader.php
src/Domain/Insights/Composer/ComposerLockMustBeFresh.php
src/Domain/Insights/Composer/ComposerMustBeValid.php
src/Domain/Insights/Composer/ComposerMustContainName.php
src/Domain/Insights/Composer/ComposerMustExist.php
src/Domain/Insights/Laravel/ComposerCheckLaravelVersion.php
src/Domain/Metrics/Architecture/Composer.php
tests/Domain/ComposerFinderTest.php
tests/Domain/ComposerLoaderTest.php
tests/Domain/Insights/Composer/ComposerLockMustBeFreshTest.php
tests/Domain/Insights/Composer/ComposerMustBeValidTest.php
tests/Domain/Insights/Composer/Fixtures/Fresh/composer.json
tests/Domain/Insights/Composer/Fixtures/Fresh/composer.lock
tests/Domain/Insights/Composer/Fixtures/Unfresh/composer.json
tests/Domain/Insights/Composer/Fixtures/Unfresh/composer.lock
tests/Domain/Insights/Composer/Fixtures/Valid/composer.json

Add new Insights about composer.
Example:
```
• [Architecture] Composer.json is not valid:
composer.json: The property name is required
composer.json: The property description is required
composer.json: No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
• [Architecture] The lock file is not up to date with the latest changes in composer.json:
You may be getting outdated dependencies. Run update to update them.
```

Add ComposerMustBeValid and ComposerLockMustBeFresh insights

---

composer.json

Just updates the phpstan-rule from localheinz reported by the dependabot.
I haven't seen any significant changes. I have only seen fixes and the addition of new rules. https://github.com/localheinz/phpstan-rules/compare/0.6.0...0.10.0

Update localheinz/phpstan-rules requirement from ^0.6.0 to ^0.10.0

---

src/Domain/Results.php
tests/Domain/ResultsTest.php
tests/Fixtures/Domain/Results/SecurityIssueComposer/composer.json
tests/Fixtures/Domain/Results/SecurityIssueComposer/composer.lock

| Fixed tickets | #172 
When ForbiddenSecurityIssues is removed in config, we caught an exception. 
This should fix it

Fix issue #172 when remove ForbiddenSecurityIssues Insight

---

docs/insights/code.md
src/Domain/Metrics/Code/Code.php
src/Domain/Metrics/Code/Functions.php

| New feature?  |no
| Fixed tickets | #177 
There are two different unused parameter sniffs in our code. 
This PR removes one of them so we don't get double reports of the same error.
resolves: #177

[Fix] Fixed the usage of two unused parameter sniffs

---

docs/insights/README.md
src/Domain/File.php
src/Domain/FileProcessor.php
src/Domain/Insights/InsightFactory.php
src/Domain/Sniffs/SniffDecorator.php
tests/Domain/Sniffs/SniffDecoratorTest.php

Here is some modifications on the original pr to ignore paths on a specific sniff: https://github.com/nunomaduro/phpinsights/pull/182.
1. Renamed `ignoreFiles` to `exclude` to be consistence with the original `exclude` that exists on the config.
2. You can also pass now the relative path, example:
```php
'config' => [
DisallowMixedTypeHintSniff::class => [
'exclude' => [
'src/Domain/Reflection.php'
],
],
```
One think I don't like: This implementation is specific to phpcs instead of being something that can be applied to all insights. What do you guys think?

Improves ignore path on specific sniff

---

src/Application/Console/Style.php
src/Domain/Exceptions/InsightClassNotFound.php
src/Domain/Results.php
tests/Domain/ResultsTest.php

| Fixed tickets | #181 
This remove mention of security issues found when we remove ForbiddenSecurityIssues Insight.
I don't know if it's the better way. I'm not huge fan of the new public function hasInsightInCategory in Results, but I wanted to leave the function getTotalSecurityIssues returning 0 even if the Insight is removed to not alter the AnalyseCommand. 
WDYT ?

Remove mention of security issue when concerning insight is removed

---

docs/insights/README.md
docs/insights/architecture.md

While browsing the `architecture section` on docs, I noticed a missing header for superfluous exception naming.
I also add an example for configure the `exclude` Insight per file, especially for "Unused Parameter" Insight because I saw it in some issues.

[Docs] missing header + add concrete example for exclude file for Sniff

---

docs/insights/complexity.md
src/Domain/Insights/CyclomaticComplexityIsHigh.php
tests/Domain/Insights/CyclomaticComplexityIsHighTest.php
tests/Domain/Insights/Fixtures/LittleToComplexClass.php
tests/Domain/Insights/Fixtures/NoCyclomaticComplexity.php
tests/Domain/Insights/Fixtures/VeryMuchToComplexClass.php

| Fixed tickets | no
I found that I wanted to change the limit of the cyclomatic complexity insight. Currently this is hard coded fixed on 5. So with this PR I add the option to change it.

Make the cyclomatic complexity limit configurable.

---

docs/get-started.md
src/Application/Console/Commands/AnalyseCommand.php
src/Domain/Insights/InsightCollectionFactory.php
src/Domain/Kernel.php
src/Infrastructure/Repositories/LocalFilesRepository.php
tests/Infrastructure/Repositories/Fixtures/FileToInspect.php
tests/Infrastructure/Repositories/LocalFilesRepositoryTest.php

| Fixed tickets | #148
This authorize the analyse of one file or a subdirectory.
To do this, I assume some Insight are "Globals" (ie all related to composer)
So when we launch an analyse on a subdirectory, I remove theses Insights in config.
For launch on a specific file, I modified the LocalFileRepository to append file directly in Finder.

Authorize analyse of one file or specific directory

---

src/Application/Adapters/Drupal/Preset.php
src/Application/Adapters/Laravel/Preset.php
src/Application/Adapters/Magento2/Preset.php
src/Application/Adapters/Symfony/Preset.php
src/Application/Adapters/Yii/Preset.php
src/Application/ConfigResolver.php
src/Application/DefaultPreset.php
src/Domain/Exceptions/PresetNotFound.php
tests/Application/ConfigResolverTest.php

| Fixed tickets | #193 (and maybe #143 #145)
:thinking: This one may be controversial
I wanted to fix #193 by adding the config for `SlevomatCodingStandard\Sniffs\Namespaces\UnusedUsesSniff` (with searchAnnotation to true) in DefaultPreset 
But I noticed that when we use an other framework preset, the config doesn't extend the default config.
After viewing issues #145, #143 and PR #111 and #147 I tried to fix them.
I before create a test that should cover all case (ie add an `exclude` path, and override a `config` value)
With the `array_replace_recursive`, we can override a config value, but we override also excluded path, so User had to rewrite the all list of exclude to bypass this problem. 
But with …

Fix default preset "use in annotation" and fix merge config 

---

composer.json

| Fixed tickets | #215
This fixes eventual deprecation errors coming from the Symplify dependencies.
Version 6.0.0 of the Symplify dependencies still uses deprecated features from the Package Builder package, which triggers an error and adds a sleep.

Bump Symplify dependencies

---

.dockerignore
.gitattributes

| Bug fix?      | Yes
| New feature?  | No
| Fixed tickets | #224

Remove the art folder when requiring the package.

---

docs/insights/README.md

I have fixed a small number of grammatical errors in the README. I have also removed the word "pimp" as it has negative connotations and does not communicate the intent of the documentation well.

Fix small number of grammatical errors in README

---

composer.json

The `docs/.vuepress/public` directory doesn't exist due to https://github.com/nunomaduro/phpinsights/pull/228. The `website:copy-logo` script will raise an error.
```bash
> @php -r "copy('CHANGELOG.md', 'docs/changelog.md');"
> @php -r "copy('art/logo_mixed.gif', 'docs/.vuepress/public/logo.gif');"
PHP Warning:  copy(docs/.vuepress/public/logo.gif): failed to open stream: No such file or directory in Command line code on line 1
PHP Stack trace:
PHP   1. {main}() Command line code:0
PHP   2. copy() Command line code:1
```
To avoid this error, we can simply check whether this directory exists and then create if it doesn't exist.
By the way, there are some merged and unused branches …

Fix copy logo script

---

phpstan.neon.dist
src/Domain/File.php
src/Domain/Metrics/Code/Comments.php

| Fixed tickets | #62 #59 and others...
This sniff `EmptyCommentSniff` doesn't work well in legacy projects. Tried to contact the owner of the project here https://github.com/slevomat/coding-standard/pull/688, but the owner doesn't have to have this sniff fixed.
The only solution, for now, is remove the sniff. What do you guys think?

fix: removes broken sniff `EmptyCommentSniff`

---

docs/get-started.md
src/Application/Adapters/Laravel/InsightsServiceProvider.php

| Bug fix?      | No
| New feature?  | No
| Fixed tickets | #235 
Following the conversion in #235 this PR updates the Laravel service provider to detect when it is being used in a Lumen application and avoid calling `$this->publishes` as the publish command is not available.
We could potentially make a separate Lumen service provider if preferred.
With the above changes in mind, I also updated the documentation to provide steps for install phpinsights in a Lumen app.

Lumen compatability

---

phpinsights.php
src/Domain/Analyser.php
src/Domain/File.php

| Fixed tickets | #59 
This PR removes the warnings thrown by PHP when a Sniff hits invalid code.

[Fix] Silence warnings

---

.travis.yml
composer.json
src/Domain/Insights/SniffDecorator.php

With latest change, phpinsights as standalone doesn't work
```
[ARCHITECTURE] 82.6 pts within 103 files
Classes ........................................................... 78.6 %
Interfaces ........................................................ 13.6 %
Globally ........................................................... 7.8 %
Traits ............................................................. 0.0 %
[MISC] 97.8 pts on coding style and 0 security issues encountered
PHP Fatal error:  Uncaught Error: Class 'Illuminate\Support\Str' not found in /home/barth/Projects/phpinsights/src/Domain/Insights/SniffDecorator.php:126
Stack trace:
#0 …
```

[HOTFIX] missing dependency illuminate str

---

README.md

| Fixed tickets |  none
This PR is meant to add a piece of small but useful information to the readme. For laravel users, you need to first publish the config file before using the package. If you don't, laravel will prompt you to by providing you with the `php artisan vendor:publish` command that will display all the current packages on your app as a list for you to select from. I believe this should immediately be pointed out in the readme so it becomes immediately obvious.

Add package publish command for laravel users to the readme file 

---

CHANGELOG.md
composer.json
docs/get-started.md
phpstan.neon.dist
src/Application/Console/Formatters/Checkstyle.php
src/Application/Console/Formatters/FormatResolver.php

Added checkstyle formatter. It needs for ci.
This reporting format also supported by phpstan (larastan).

Add checkstyle formatter

---

.travis.yml

| Fixed tickets | #278 
Every time a new tag is deployed, it was not generated in the dockerhub according to github.
Now every time a new tag is deployed, a tag from the current version and a latest tag will be generated.
This resolves issue # 278

Fix when generating a tag in docker hub (#278)

---

CHANGELOG.md
docs/package.json
src/Domain/Kernel.php

Looks we we forgot to bump the version to v1.9.0 :) 
Also the changelog was referencing a version we haven't released yet, so I changed it to the support `Unreleased` tag from Keep A Changelog

[Chore] bump version to v1.9.0

---

config/container.php
src/Application/Adapters/Laravel/Commands/InsightsCommand.php
src/Application/ConfigResolver.php
src/Application/Console/Analyser.php
src/Application/Console/Commands/AnalyseCommand.php
src/Application/Console/Commands/InvokableCommand.php
src/Application/Console/Definitions/AnalyseDefinition.php
src/Application/DirectoryResolver.php
src/Application/Injectors/Configuration.php
src/Domain/Configuration.php
src/Domain/Contracts/InsightLoader.php
src/Domain/Exceptions/InvalidConfiguration.php
src/Domain/Insights/InsightCollectionFactory.php
src/Domain/Insights/InsightFactory.php
tests/Application/ConfigResolverTest.php
tests/Domain/Insights/CyclomaticComplexityIsHighTest.php
tests/Domain/Insights/InsightFactoryTest.php
tests/TestCase.php

In order to fix this [comment](https://github.com/nunomaduro/phpinsights/pull/265#discussion_r324466057), I add a Configuration Class that carry config provided by user.
The Configuration class is resolved when container boot, so we can use DependencyInjection or container to retrieve configuration. 
So we don't have anymore the need to manually pass config everywhere we need it. 
As phpcsfixer came with it, I use [symfony/options-resolver](https://symfony.com/doc/current/components/options_resolver.hml) to improve configuration validation.
I think this refact is needed, because the config file is growing, and we should have a simpler way to validate it, and also retrieve it. 
WDYT …

[Refact] configuration class

---

src/Application/Adapters/Laravel/Commands/InsightsCommand.php

| Fixed tickets | #286 
When we add a service into container, it is not replaced if it was precedently defined.
So we need to replace concrete class of definition. 
Ping @akosglue

Fix laravel configuration resolution - #286

---

src/Infrastructure/Repositories/LocalFilesRepository.php
tests/Infrastructure/Repositories/LocalFilesRepositoryTest.php

Bug introduced in #291. When we use `append` in Finder, it return an \AppendIterator fill of `\SplFileInfo` instead of `Symfony\Component\Finder\SplFileInfo`.

Fix analyse on one file

---

docs/insights/code.md

fix docs for `Modern ClassName reference` section

add inline code for code.md

---

src/Application/Console/Commands/AnalyseCommand.php

I noticed when display all issues, sometimes the 'tip' for send issue or pull request appear in issues flow.
Fixed by not using errorOuput when use consoleFormatter

Fix display tip repo when format is console

---

docs/insights/code.md
src/Domain/Metrics/Code/Comments.php

This pull request fixes the fact that the EmptyComment sniff is duplicated with NoEmptyComment from php cs fixer.

fix: removes duplicated no empty comment sniff

---

src/Application/Adapters/Laravel/Preset.php

Avoids having drama about typehints on the laravel preset.

fix: removes void return fixer from laravel preset

---

src/Domain/Configuration.php
tests/Domain/ConfigurationTest.php

| Fixed tickets | #318 
In default stub, we add `'ide' => null` to configure url handle. However, this null value wasn't catched. 
This is now fixed

[Fix]  assert ide is defined before resolving it

---

.travis.yml

I just test phpinsights locally on php7.4, everything went well :clap: 
So I just add it to travis to keep things working

Add php7.4 on travis ci

---

src/Domain/Insights/ForbiddenFinalClasses.php
src/Domain/Insights/Insight.php
src/Domain/Metrics/Architecture/Classes.php
tests/Domain/Insights/Fixtures/ForbiddenFinalClass.php
tests/Domain/Insights/ForbiddenFinalClassTest.php

[Fix] Forbidden final classes exclude

---

src/Domain/Analyser.php
tests/Domain/Insights/EmptyNamespaceTest.php
tests/Domain/Insights/Fixtures/EmptyNamespaceFile.php

Prevent failing addNamespace method

---

docs/continuous-integration.md

I noticed that the version for github formatter is wrong in documentation. v1.12 was released without this feature. 
Now the PR #344 is merged, we can assume it'll be in v1.13 :tada:

docs: Fix version for using github formatter

---

src/Application/Adapters/Laravel/Preset.php

Add ddd and tinker to forbidden methods.
- `ddd` is from ignition, the error page package for Laravel
- `tinker` is from tinkerwell, the tinkering tool for Laravel

feat(laravel-preset): Add forbidden methods

---

composer.json
docs/get-started.md

| Fixed tickets | #368
This PR add support for Laravel 7.
`phploc/phploc` was updated to `^5.0|^6.0` as only version 6.0 supports `symfony/console` 6
I had to downgrade `minimum stablility` to `RC` because `composer/composer` has no stable version supporting `symfony/console` 6 but there is a `1.10.0-RC` version. See on [packagist](https://packagist.org/packages/composer/composer)

Add support for Laravel 7

---

composer.json
docs/continuous-integration.md
phpinsights.php
src/Application/Adapters/Laravel/Commands/InsightsCommand.php
src/Application/ConfigResolver.php
src/Application/Console/Commands/AnalyseCommand.php
src/Application/DirectoryResolver.php
src/Application/Injectors/Configuration.php
src/Domain/Configuration.php
stubs/config.php
stubs/drupal.php
stubs/laravel.php
stubs/magento2.php
stubs/symfony.php
tests/Application/ConfigResolverTest.php
tests/Domain/Insights/InsightFactoryTest.php
tests/Fakes/FakeInput.php
tests/TestCase.php

| Fixed tickets |  #361 
This PR makes min-requirements configurable via configuration file

feat(config): make min-requirements configurable through file

---

src/Domain/Insights/FixerDecorator.php

This pull request aggregates diffs of the same file in the same error:
Previous, we were advising users to remove code ( that was added on the omitted issues ).

fix(diffs-displays): aggregates diffs in the same error

---

src/Domain/ComposerLoader.php
src/Domain/Contracts/Repositories/FilesRepository.php
src/Domain/FileProcessors/FixerFileProcessor.php
src/Domain/Helper/Files.php
src/Domain/Insights/Composer/ComposerMustBeValid.php
src/Domain/Insights/Composer/ComposerMustContainName.php
src/Domain/Insights/Composer/ComposerMustExist.php
src/Domain/Insights/InsightCollection.php
src/Domain/Insights/InsightCollectionFactory.php
src/Domain/Runner.php
src/Infrastructure/Repositories/LocalFilesRepository.php
tests/Fakes/FakeFileRepository.php
tests/Infrastructure/Repositories/LocalFilesRepositoryTest.php

Hey :wave: 
Past days, I continued to play with blackfire to see how we can speed up PHPInsights.
I found some ways:  
Using Symfony Finder cost a lot, particulary when we had to call an iterator_to_array on it.
We call severall times hasIssue on Insights during process, and some of them had huge task to calculate issues. 
Same for Results from InsightsCollection, called twice with lot of foreach inside.  
You can check the comparison between master branch and mine:  https://blackfire.io/profiles/compare/4c42280b-0b72-435d-956e-d54afb4b82fe/graph
I gain 26% of time speed :raised_hands:

[Improvment] Performances

---

src/Domain/File.php
src/Domain/FileFactory.php

Looking at a [blackfire analysis](https://blackfire.io/profiles/0cdf3b41-a85d-4b3e-95c1-ce0c2e281df8/graph), I saw that we spent roughly 10% constructing PHPCS ruleset for each file
However a ruleset is not bound to a file, so this change does so we only create one ruleset and use that for each file, hence saving a lot of time.
A comparison of can be found [here](https://blackfire.io/profiles/compare/ecc5008d-6cc2-4b8d-bb23-5e59608e842e/graph).
Thanks @Jibbarth for reminding me about blackfire ❤️

feat(ruleset): Only instantiate ruleset once

---

src/Domain/Insights/Composer/ComposerLockMustBeFresh.php

If you run php insights on a project that does not contain a `composer.lock` file it will fail, this add's a check for the lock file also.

fix(composer): Check that lock file exist

---

src/Application/Console/Formatters/Console.php

Just noticed when an Insight has issue without file associated in Detail, there is a weird render:
This fix that:

Fix display detail message without file

---

src/Domain/Insights/SniffDecorator.php
src/Domain/Runner.php

I noticed analysing with blackfire that set_error_handler is called multiple times.
By moving it from sniffDecorator to Runner, we gain 61% of memory usage. 
See the [blackfire compare profile](https://blackfire.io/profiles/compare/06a83806-75e0-4ed5-9247-9a4ef8cb7aab/graph)
@50bhan, as you added it in #358, could you please check if everything is okay for you with that change ? 🙏

[Improvement] Reduce set_error_handler call

---

src/Domain/Insights/ForbiddenSecurityIssues.php

User experiment improve. 
I noticed the ForbiddenSecurity check, that call an external webservice, may brievly stop display resume. 
By defining it as GlobalInsight, it'll be launched during analyse, so there is no more stop after. 
Demo with a slow 2G connection:

[UX] launch securitycheck as global

---

docs/insights/style.md

[ordered_imports] Invalid configuration: The option "import_order" does not exist. Defined options are: "imports_order", "sort_algorithm".

Small typo fix

---

src/Application/Console/Formatters/Console.php

I noticed that IDE link doesn't longer work since we add color on files.
This PR fix it :

Fix ide link with colors

---

src/Domain/Insights/SyntaxCheck.php
src/Infrastructure/Repositories/LocalFilesRepository.php

| Bug fix?      | yes (on dev-master)
While @ekvedaras was testing parallelization on windows, a new bug came out (cf https://github.com/nunomaduro/phpinsights/pull/414#issuecomment-688075910) 
When we are launching SyntaxCheck on a large project with Windows, passing all files to inspect as arg may create a too long command for this system.
Here, I refact how we launch it. Instead passing all files as arg, we now excludes directory or files from configuration, and pass the current analysed path.

Fix SyntaxCheck launch with windows on large project

---

src/Domain/Insights/ForbiddenSecurityIssues.php

| Fixed tickets | #438 
The getDetails method already handle catch InternetConnectionNotFound

Refs #438 - Fix exception thrown when no internet connection

---

src/Application/Console/Formatters/Console.php
src/Application/Console/Formatters/FormatResolver.php
src/Application/Console/Formatters/GithubAction.php
tests/Application/Console/Formatters/FormatResolverTest.php

I noticed we can no longer use `json` or `checkstyle` formatter cause their constructors changed in #391 
This PR fix that by looking with a reflection how many parameters has formatter. 
I also added tests to avoid future regression on this :sweat_smile:

Fix changing formatter

---

src/Domain/ComposerLoader.php

I was working on add compat with php8 and migrate CI to github action (you can see progress [here](https://github.com/Jibbarth/phpinsights/pull/1)) when composer v2 was released, and all my builds breaks :sweat_smile: 
After investigating, an fullload option is passed in createComposer when calling `Factory::create` to retrieve a Composer object, and this fullLoad option use somewhere the global composer binary...
I change the way to call ComposerFactory, to avoid having this `fullLoad` option to true, and I create manually the Locker (it was only created with fullLoad on true before).

Fix ComposerLoader when composer:V2 is installed globally

---

CHANGELOG.md
composer.json
src/Domain/Insights/ForbiddenSecurityIssues.php
tests/Domain/Insights/Composer/Fixtures/LargeLockFile/composer.lock
tests/Domain/Insights/Composer/Fixtures/Vulnerable/composer.json
tests/Domain/Insights/Composer/Fixtures/Vulnerable/composer.lock
tests/Domain/Insights/ForbiddenSecurityIssuesTest.php

| Bug fix?      | It will prevent one
Hi :wave: 
This is related to announce that [Sensiolabs/Security-checker](https://github.com/sensiolabs/security-checker) API will be stop (see anounce here : https://twitter.com/fabpot/status/1349980977397964800)
I first thought to remove this Insight, but I finally discover that packagist provide an api to get security advisories : https://repo.packagist.org/apidoc#list-security-advisories
So I decided to remove dependency to security-checker, and and call this API by ourselves. 
I targetted the 1.x branch, because the actually used API will be stop at the end of january, so I think we should release a 1.14.1 patch, and if accepted, I will backport this patch to …

[SecurityCheck] Switch service to discover vulnerabilities

---

.github/workflows/format.yaml

This avoid to launch PHP Insight with list of modified file when it's not a pull request workflow.

[CI] Avoid launch on modified file if not a PR

---

src/Application/Console/Formatters/Checkstyle.php

| Fixed tickets | #463 
Convert "source" attribute in Checkstyle report to dot notation.
Apply the change as advised in https://github.com/nunomaduro/phpinsights/issues/463#issuecomment-791896035
This will allow Checkstyle parsing tools to get the category and type of the issue.
The checkstyle output before
```
<error severity="error" source="Forbidden setter" line="227"
message="Setters are not allowed. Use constructor injection and behavior naming instead."/>
```
and after the change
```
<error severity="error" source="NunoMaduro.PhpInsights.Domain.Sniffs.ForbiddenSetterSniff" line="227"
message="Setters are not allowed. Use constructor injection and behavior naming instead."/>
```
Also Jenkins Warnings …

fix: Convert Checkstyle's source attribute to dot notation format

---

phpinsights.php
src/Domain/Collector.php
src/Domain/Insights/CyclomaticComplexityIsHigh.php
tests/Domain/Insights/CyclomaticComplexityIsHighTest.php

| Fixed tickets | #458, #422, #367
Hi :wave: 
This PR to add some improvement for Cyclomatic Complexity. 
First, as pointed in #458, the Insight title still appear even if we exclude all problematic files in config. 
This is because the hasIssue method didn't take account of getDetails method. 
Then, I added in the collector a way to remove from complexity calc all files excluded. 
In effect, when we DECIDE to exclude a file, the calculator SHOULD don't take it in account.
**Note for users:** 
To get 100points in complexity score, you need to have an averrage cyclomatic complexity of 1.00. 
So even you raise maxComplexity limit, your score is caclculated on the averrage cyclomatic complexity, and your …

[Cyclomatic Complexity] Improvements

---

src/Application/Console/Definitions/AnalyseDefinition.php

It seems the signature of `InputOption` has been changed from `string|string[]|int|bool|null` to `string|string[]|bool|null` in the latest release.
Reference: https://github.com/symfony/console/commit/3c65c2dda22b7794dde8dd5e0c2f7b5542ae0d2c
This PR will fix this issue by passing a string instead of an integer.

Change Symfony console `InputOption` default value from int to string

---

composer.json

Currently installing `PhpInsights` dev dependencies is not possible on PHP v.8 and you'll get the below error:
```
Problem 1
- ergebnis/phpstan-rules[0.14.0, ..., 0.14.1] require php ^7.2 -> your php version (8.0.1) does not satisfy that requirement.
- ergebnis/phpstan-rules[0.14.2, ..., 0.14.4] require php ^7.1 -> your php version (8.0.1) does not satisfy that requirement.
- Root composer.json requires ergebnis/phpstan-rules ^0.14.0 -> satisfiable by ergebnis/phpstan-rules[0.14.0, ..., 0.14.4].
```
So we need to bump the dependency version up to allow this package to install on PHP v.8.
Reference: https://github.com/ergebnis/phpstan-rules/pull/294

Update a composer dev dependency to avoid failure on PHP v.8

---

.github/workflows/standalone.yaml
.github/workflows/test.yaml

The symfony/cache-contract v2.4.0 (released yesterday https://github.com/symfony/cache-contracts/releases/tag/v2.4.0) enable v2 and v3 of psr/cache, that require php8.0. 
As we had some composer install `ignore-platform-reqs`, all build are broken :sweat_smile: .
Let's see if we remove it fix all stuff :crossed_fingers:

Github workflow - Remove ignore-platform-reqs in composer install

---

.github/workflows/format.yaml
src/Application/Adapters/Laravel/Commands/InsightsCommand.php
src/Application/Console/Commands/InvokableCommand.php
src/Application/Console/Definitions/AnalyseDefinition.php
src/Application/Console/Definitions/BaseDefinition.php
src/Application/Console/Formatters/Console.php

:wave: 
A little tiny feature that enable to only show summary. 
It could be usefull when, for example, you want to display a real-time monitor while you code. 
See video below :wink: 
https://user-images.githubusercontent.com/3168281/116463767-625a8a80-a86b-11eb-9ae7-e69b27bb74ca.mp4
If you want reproduce this, I used the `watch` command : 
```bash
watch -c -b php vendor/bin/phpinsights -s --ansi
```
With this PR, I also improve the `fix` output: Display first the recap, then files fixed, then total issues remaining. I think it's less confusing.

[Feature] Add option to show summary only

---

.github/workflows/frameworks.yaml
docs/get-started.md
src/Application/Adapters/Laravel/Commands/InsightsCommand.php
src/Application/Console/Formatters/Console.php
src/Application/Injectors/Configuration.php
src/Domain/Configuration.php
src/Domain/Differ.php
src/Domain/Insights/FixerDecorator.php
tests/Application/ConfigResolverTest.php
tests/Domain/ConfigurationTest.php

:wave: 
This PR to improve display for diff. 
By default, I add 1 line of context around the diff. I also improve the default display by removing some empty lines.
**Before:**
**After:**
But, now, we can configure the diff context around. 
In `phpinsights.php`, add the following line: 
```php
<?php
return [
// ...
'diff_context' => 3,
]
```
**Output:**
While testing, I noticed that when configuration file has some invalid options, the output was really ugly: 
I rework a little this part to improve output when there is an invalid configuration:

[Feature] Diff output configurable

---

src/Domain/Insights/SyntaxCheck.php
tests/Domain/Insights/Fixtures/InvalidPhpCode/_ide_helper.php
tests/Domain/Insights/SyntaxCheckTest.php

| Fixed tickets | #486
This fixes a few issues with SyntaxCheck introduced in #437 and #448 that together resulted in files from the config's top-level `exclude` option not being excluded.
```php
return ['preset' => 'laravel', 'exclude' => ['foo.php']];
```
```sh
/usr/bin/php '/foo/vendor/bin/parallel-lint' --no-colors --no-progress --json \
--exclude 'vendor' --exclude 'tests' --exclude 'Tests' --exclude 'test' --exclude 'Test' .
```
```sh
/usr/bin/php '/foo/vendor/bin/parallel-lint' --no-colors --no-progress --json \
--exclude 'bower_components' --exclude 'node_modules' --exclude 'vendor' --exclude '.phpstorm.meta.php' \
--exclude 'config' --exclude 'storage' --exclude 'resources' --exclude 'bootstrap' …
```

[SyntaxCheck] Fix `exclude`s from config/preset not being applied

---

.github/workflows/frameworks.yaml
.github/workflows/standalone.yaml
.github/workflows/test.yaml
bin/phpinsights
composer.json
phpstan.neon
src/Application/Adapters/Laravel/Commands/InsightsCommand.php
src/Application/Injectors/Configuration.php
src/Domain/ComposerLoader.php
src/Domain/Differ.php
src/Domain/Insights/FixerDecorator.php
src/Domain/Metrics/Style/Style.php

| Fixed tickets | #476
This PR will close #476. 
- As @Jibbarth said here https://github.com/nunomaduro/phpinsights/issues/476#issuecomment-838825297, due to replacing `php-cs-fixer` and `php-codesniffer` by `symplify/easy-coding-standard`, I believe we need to remove it. 
- `php-cs-fixer` in version 3.0 is using `"composer/xdebug-handler": "^2.0"`, and composer in version 2.0 is still using `"composer/xdebug-handler": "^1.1"`. So, we need to wait for new release of composer.
- There are some changes in the new version are `Rector` that have been applied.
- There are some changes in `php-cs-fixer` interfaces that need to be applied.

Upgrade dependencies (PHP-CS-Fixer v3)

---

docs/insights/README.md
src/Domain/InsightLoader/FixerLoader.php

This adds support for controlling the WhitespacesFixerConfig for fixers implementing WhitespacesAwareFixerInterface.
| Fixed tickets | #451
This PR implements the second option discussed in #451 (Per fixer config).

Feature: support configuring fixer indentation

---

composer.json
src/Infrastructure/Repositories/LocalFilesRepository.php

| Fixed tickets | #508
This PR will close #508.

Fix path resolver when path start with directory separator

---

docs/get-started.md

| Fixed tickets | no |
The docker example uses `pwd`, but it is not wrapped in quotes `"`.
If the path returned by `pwd` contains a space character, docker will have an error:
> docker: invalid reference format.
For people less familiar with docker, it can be quite unclear what is going wrong.
This MR fixes that issue by wrapping the call in quotes, so the path is passed to docker properly.

docs: Change docker example to be more robust.

---

src/Application/DefaultPreset.php
src/Domain/Insights/SyntaxCheck.php

| Fixed tickets | Fix #504
As @tarlepp indicate in #504, when we install phpinsights through bamarni composer plugin, the SyntaxCheck Insight is unable to find the correct path for using parallel-lint. 
This PR should fix that

Fix retrieving composer binary path in SyntaxCheck

---

docs/continuous-integration.md

Not a big deal. Not important, but as PHP 8 is supported, we could show the usage of PHP 8.0 in the docs.

Update the GitHub Actions example to PHP 8

---

docs/continuous-integration.md

As version 1 is deprecated, we should use version 2 in the docs. 
There are no breaking changes if using GitHub Actions as shown in the docs.

[Docs] Upgrade to setup-php version 2

---

src/Application/Console/Definitions/AnalyseDefinition.php

adding missing `github-action` format to `help` message.
it is described in the documentation for CI:
https://phpinsights.com/continuous-integration.html#github-action
but is not present on the help output, so it can lead to some people
making some awkward `jq` transformations on theirs workflows.

(fix): add "github-action" as a format option

---

composer.json
rector.php
src/Application/ConfigResolver.php
src/Application/Console/Commands/InternalProcessorCommand.php
src/Domain/Collector.php
src/Domain/File.php
src/Domain/InsightLoader/FixerLoader.php
src/Domain/Insights/Composer/ComposerLockMustBeFresh.php
src/Domain/Insights/Composer/ComposerMustBeValid.php
src/Domain/Insights/CyclomaticComplexityIsHigh.php
src/Domain/Insights/FixerDecorator.php
src/Domain/Insights/ForbiddenDefineFunctions.php
src/Domain/Insights/ForbiddenDefineGlobalConstants.php
src/Domain/Insights/ForbiddenGlobals.php
src/Domain/Insights/ForbiddenNormalClasses.php
src/Domain/Insights/ForbiddenTraits.php
src/Domain/Insights/Insight.php
src/Domain/Insights/SniffDecorator.php
src/Domain/Insights/SyntaxCheck.php
src/Domain/Metrics/Architecture/Classes.php
src/Domain/Metrics/Architecture/Globally.php
src/Domain/Metrics/Architecture/Interfaces.php
src/Domain/Metrics/Architecture/Traits.php
src/Domain/Runner.php

| QA      | yes
This PR apply to latest rector and update to use latest rector compatible config:
- bootstrapping files via Option::BOOTSTRAP_FILES config.
- remove deprecated cache Option:: ENABLE_CACHE config as cached by default.
- skip `RemoveUnusedPromotedPropertyRector` as phpinsights still support php 7.4.
- run the rector.

[Rector] Apply Latest Rector 

---

.github/workflows/frameworks.yaml
.github/workflows/standalone.yaml
.github/workflows/test.yaml
composer.json

Allow Symfony 6 dependencies
Currently, the `php-cs-fixer` don't allow it yet, but I believe the upgrade will be made soon.
Also add PHP8.1 in workflow to be sure the tool still work on PHP8.1, and guess what ? It works :raised_hands:

Get ready for PHP8.1 and SF6

---

src/Application/Console/Formatters/CodeClimate.php

| Fixed tickets | #526
Actually, I was wrong (see #526 ), there is only "severity" field was missing 
https://docs.gitlab.com/ee/user/project/merge_requests/code_quality.html#configuring-jobs-using-variables
Works fine on GitLab Community Edition 13.12.0

Fix missing fields for CodeClimate formatter

---

src/Domain/ComposerLoader.php

| Fixed tickets | #565 
This is a simple fix in an attempt to get the package working when minimum-stability is set to "dev" in composer.json and doesnt address input from Jordi Boggiano in https://github.com/nunomaduro/phpinsights/issues/559

fix(ComposerLoader): use full load to avoid that when using composer/composer ^2.3 a PartialComposer is returned

---

docker/Dockerfile

| Fixed tickets | #556
Bumping to PHP 8.0 fixes the `Syntax error` as mentioned in the issue. The new docker tag has been pushed already. 
I'm going to hold off on multiple docker images/tags for different PHP versions until we see how this fix goes.

bump docker to php 8.0, fixes #556

---

docs/insights/style.md

- Upon running this fixer and trying to modify the order of class elements the key taken from the docs of `sortAlgorithm` ended up not being correct. The correct key for this fixer is snake cased as `sort_algorithm`. This PR will fix this problem.

Update config key for ordered class elements fixer

---

.github/workflows/frameworks.yaml

| Fixed tickets | na
GH Actions only took into account Laravel 8 and `dev-master`. This PR updates the action to include Laravel 9

add laravel 9 to GH actions test suite

---

.github/workflows/frameworks.yaml
composer.json

| Fixed tickets | #522 #573 
Allows installation of `psr/simple-cache` in versions `^2.0` and `^3.0`

Allow psr/simple-cache ^2.0 and ^3.0

---

src/Domain/Kernel.php

| Fixed tickets | #517
Refs issue #517
When we remove `PHP_CodeSniffer\Standards\PSR2\Sniffs\Classes\PropertyDeclarationSniff::class`, the `PHP_CodeSniffer\Util\Tokens` class is not called. Other sniffs may use Tokens defined in this file, without requiring it, and lead to an error. 
Requiring file into Kernel allow to have all theses tokens defined anyway.

Fix #517 by always loading CodeSniffer tokens

---

src/Application/Console/Formatters/Json.php
tests/Application/Console/Formatters/JsonTest.php

| Fixed tickets | #519
As asked in #519, handle summary option also in JsonFormatter

Refs #519 - handle summary option in JsonFormatter

---

src/Application/Adapters/WordPress/Preset.php
src/Application/ConfigResolver.php
stubs/wordpress.php
tests/Application/ConfigResolverTest.php
tests/Fixtures/ConfigResolver/ComposerWordPress/composer.json

| Fixed tickets | #35 
This is a feature for WordPress adapter. There is a small caveat - it currently works on [Bedrock](https://roots.io/bedrock/) version of WordPress (and `johnpbloch/wordpress` package). That is I haven't tested this on my plugin for instance, I'll do this later.
I only added config resolver test, not sure if I need to add anything else 🤷🏼‍♂️

Add WordPress adapter

---

composer.json

| Fixed tickets |
Fixing "LogicException Unable to find data for ..." last days error. It happens, because transitive dependency php-cs-fixer/diff was removed. It was used in phpinsights, but not stated in composer.json.
All fresh installation, where `php-cs-fixer/diff` required directly or where older version of phpcs is fixed, don't work anymore.
https://github.com/FriendsOfPHP/PHP-CS-Fixer/commit/b3cc7ef69fd67b9b2c156329a3e820667a0c800a#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34L23-R23

Fixing "LogicException Unable to find data for ..." by adding required dependencies

---

.github/workflows/frameworks.yaml
src/Application/Adapters/WordPress/Preset.php
src/Domain/Insights/SyntaxCheck.php

Update GH actions to run successfully

---

src/Application/Console/Formatters/Console.php

Changed the foreground color of the box labels for Code, Complexity, Achitecture, and Style from black to white because for some reason on Windows (10) systems black as foreground color doesn't seem to work (see #37).
| Fixed tickets | #37
On Windows (10), the "black" foreground color of the box labels isn't shown as black, but as some kind of medium gray that is almost invisible on a green background and isn't readable on yellow and possibly most other background colors. Changing the foreground color for the box labels to white instead leads to easily readable labels.

Resolves #37 - Changed the foreground color of the box labels to white (Windows issue)

---

docs/insights/README.md

There was a typo in the class name, which has been corrected.

docs: fixed typo

---

stubs/config.php
stubs/drupal.php
stubs/laravel.php
stubs/magento2.php
stubs/symfony.php

I just fixed a minor typo in the stub files. I also replaced "This" with "It" so that each line is exactly 3 chars less than the previous one.

Fixes typos in stub files.

---

composer.json

| Fixed tickets | #604
Bumps dependency on slevomat/coding-standard to ^8.0

Added support for slevomat/coding-standard:8.0

---

.github/workflows/format.yaml
.github/workflows/frameworks.yaml
.github/workflows/standalone.yaml
.github/workflows/test.yaml
phpinsights.php

This PR updates GH actions to run PHP 8.2, and uses new action versions for checking out and caching

update GH actions

---

composer.json
phpunit.xml

I added support for Laravel 10 as well as PHP 8.1. It was also necessary to change the 'min-style' from 98 to 96, because the Test Workflow in macos-latest with PHP 7.4 was not passing.

Added Laravel 10 and PHP 8.1 Support

---

src/Application/Console/Formatters/Console.php
src/Domain/Insights/CyclomaticComplexityIsHigh.php
src/Domain/Insights/ForbiddenGlobals.php
src/Domain/Insights/ForbiddenSecurityIssues.php
src/Domain/Results.php

Unwraps string interpolation from deprecated `"${var}"` to `"$var"`.
Resolves #615

fix string interpolation deprecation messages in PHP 8.2

---

src/Application/Console/Formatters/Console.php
src/Domain/Insights/CyclomaticComplexityIsHigh.php
src/Domain/Insights/ForbiddenGlobals.php
src/Domain/Insights/ForbiddenSecurityIssues.php
src/Domain/Results.php

Continuation of #628. Interpolation is still allowed in [8.2](https://php.watch/versions/8.2/$%7Bvar%7D-string-interpolation-deprecated) if the braces include the `$`.

Adjust interpolation

---

.gitignore
composer.json
phpunit.xml
src/Domain/Analyser.php
tests/Domain/Insights/Fixtures/ReadonlyClass.php
tests/Domain/Insights/ReadonlyClassTest.php
tests/Domain/Insights/SyntaxCheckTest.php

| Fixed tickets | #637 
So this fix the `[Architecture] Normal classes are forbidden. Classes must be final or abstract` error message.
To fix the `[Style] Side effects` this [PR](https://github.com/squizlabs/PHP_CodeSniffer/pull/3728) to PHP_CodeSniffer SideEffectsSniff is currently being made and reviewed following this [issue](https://github.com/squizlabs/PHP_CodeSniffer/issues/3727)
I'm not quite sur about how to create tests for this new behavior as I haven't seen any test for the currently working behavior.
But I'd be happy to be wrong about this statement and to be showed which test I should update !

fix readonly final class architecture side effect issue PHP8.2

---

src/Domain/Insights/SyntaxCheck.php

| Fixed tickets | #644
This PR allows to escape binary path where php binary like this : 
`/Users/<username>/Library/Application Support/Herd/bin/php82`
We have a space between Application and Support and without quotes, Process stop at `/Users/<username>/Library/Application` and can't find php executable

add quotes around binary path

---

src/Domain/Configuration.php

Hello, 
This is fixing an issue where phpinsights can't be run when setting preset as `wordpress` in phpinsights.php config file. WordPress preset was added in #378 
Actual error: 
```
Invalid configuration 
• The option "preset" with value "wordpress" is invalid. Accepted values are: "drupal", "laravel", "symfony", "yii", "magento2", "default".
```
| Fixed tickets |

Fix error: The option "preset" with value "wordpress" is invalid

---

composer.json
src/Application/DefaultPreset.php

| Fixed tickets | 
Removing the default for a non-existing property newlinesCountBetweenOpenTagAndDeclare in DeclareStrictTypesSniff  (https://github.com/slevomat/coding-standard/blob/master/SlevomatCodingStandard/Sniffs/TypeHints/DeclareStrictTypesSniff.php) that gives an deprecation notice in PHP 8.2.

Fix non-existing default property

---

src/Domain/InsightLoader/SniffLoader.php
src/Domain/Insights/SniffDecorator.php

| Fixed tickets | #647
This change is a more generic solution for #647 to solve the dynamic properties deprecation notice in PHP 8.2.

PHP 8.2 fix for dynamic property $exclude

---

src/Domain/Runner.php

| Fixed tickets | #609
This should fix #609.
Maybe not directly but it should make the initial error bubble up allowing the user to fix it or report it properly instead of having an "Unable to find data for" error.
For example:
```
0/2205 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0%
In Runner.php line 163:
The command "'/opt/homebrew/Cellar/php@8.1/8.1.17/bin/php' '[...]/vendor/bin/phpinsights' 'internal:processors' 'thread-1-fd43f7fb701672bfec0768e9b3d9828c'" failed.
Exit Code: 255(Unknown error)
Working directory: [...]
Output:
================
Fatal error: Allowed memory size of 33554432 bytes exhausted (tried to allocate 135168 bytes) in [...]/vendor-bin/phpinsights/vendor/squizlabs/php_codesniffer/src/Tokenize …
```

Prevent the runner to swallow its threads error

---

src/Infrastructure/Repositories/LocalFilesRepository.php

| Fixed tickets | #662
Disable `symfony/finder` ignore defaults for single files.

disable default ignore for dot/vcs files for single files

---

src/Domain/Insights/SniffDecorator.php

Fixed type error
Error: Method NunoMaduro\PhpInsights\Domain\Insights\SniffDecorator::register() should return array<string> but returns array<int|string>.
https://github.com/nunomaduro/phpinsights/pull/692/checks

Fixed type error

---

src/Application/DefaultPreset.php

See https://github.com/slevomat/coding-standard/commit/b71f8d788e81021be0bb8a7327aced7f952e2f87 The property we set has been renamed since V7 of slevomat coding standard
| Fixed tickets | #695

Refs #695 - Fix deprecation for dynamic property

---

src/Domain/Runner.php

Addresses nunomaduro/phpinsights#511
| Fixed tickets | #511
Implements what the above comment says, such that cache is only checked when not fixing (but I guess only analyzing).
This solves an intermittent (yet persistent for some) problem where fixing some files triggers an error and breaks the process.

Check Cache Only When Not Fixing
